export interface ChronoTheraAssetPreset { id:string; label:string; category:string; modality:string; default_apis:string[]; suggested_routes:string[]; formulation_objectives:string[]; chronothera_focus:string[]; dossier_anchor?:string }
export interface ChronoTheraExcipientStrategy { name:string; default_percentage:number; class:string; function:string }
export interface ChronoTheraCatalog { assets: ChronoTheraAssetPreset[]; excipient_strategies: ChronoTheraExcipientStrategy[]; formulation_objectives: string[]; routes: string[]; regulatory_bodies: string[] }
export interface ChronoTheraApiComponent { name:string; dose_mg:number; modality?:string }
export interface ChronoTheraExcipientComponent { name:string; percentage:number; function?:string }
export interface ChronoTheraSimulationPayload { asset_id?:string; program_id?:string; formulation_objective:string; apis: ChronoTheraApiComponent[]; excipients: ChronoTheraExcipientComponent[]; release_duration_weeks:number; route_of_administration:string; regulatory_body:string; strategy_mode:'cooperative'|'competitive'; optimize_excipient_percentages:boolean; pkpd_objective:{ target_exposure:string; dosing_interval_days:number; peak_to_trough_priority:number; adherence_priority:number } }
export interface ScoreExplanation { score:number; rationale:string; assumptions:string[]; uncertainty:string[]; recommendation:string; next_best_step:string }
export interface ChronoTheraSimulation { id:string; created_at:string; asset_id?:string; program_id?:string; input: ChronoTheraSimulationPayload; release_profile:{ labels:string[]; datasets:{ api:string; cumulative_release:number[]; model:string; rationale:string }[] }; scorecard: Record<string, ScoreExplanation>; overall_chronothera_score:number; formulation_delivery_profile: Record<string, unknown>; epistemic_trace:{ zone_cluster:string; zones:string[]; cxus:{ id:string; name:string; question:string; confidence:number; uncertainty:string[] }[]; swarm:{ id:string; mode:string; participants:string[]; consensus_score:number; consensus_rationale:string }; provenance:{ input_hash:string; output_hash:string; model_engine_version:string; timestamp:string; assumptions:string[]; uncertainty_reasons:string[] } }; guardian_review:{ required:boolean; status:string; reasons:string[]; reviewer?:string; notes?:string; reviewed_at?:string }; disclaimer:string }
export interface GuardianReviewPayload { decision:'approved'|'needs-revision'|'rejected'; reviewer:string; notes:string }
