import React from 'react';
import fs from 'node:fs';
import path from 'node:path';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi, beforeEach } from 'vitest';
import { ChronoTheraApp } from '@/components/chronothera/ChronoTheraApp';
import { ChronoTheraScorecard } from '@/components/chronothera/ChronoTheraScorecard';
import { EpistemicTracePanel } from '@/components/chronothera/EpistemicTracePanel';
import { GuardianReviewPanel } from '@/components/chronothera/GuardianReviewPanel';
import { JsonExportButton } from '@/components/chronothera/JsonExportButton';
import type { ChronoTheraCatalog, ChronoTheraSimulation } from '@/lib/types/chronothera';

vi.mock('recharts', () => ({ ResponsiveContainer: ({ children }: any) => <div>{children}</div>, LineChart: ({ children }: any) => <div>{children}</div>, Line: () => <div />, XAxis: () => <div />, YAxis: () => <div />, Tooltip: () => <div /> }));

const catalog: ChronoTheraCatalog = { assets:[{ id:'a1', label:'Asset One', category:'Category A', modality:'peptide', default_apis:['API One'], suggested_routes:['SC'], formulation_objectives:['sustained_release'], chronothera_focus:['oncology'], dossier_anchor:'forge/a1' }], excipient_strategies:[{ name:'PLGA', default_percentage:35, class:'polymer', function:'depot/sustained release' }], formulation_objectives:['sustained_release'], routes:['SC','oral'], regulatory_bodies:['FDA'] };
const simulation: ChronoTheraSimulation = { id:'chrono-1', created_at:'2026-01-01T00:00:00Z', asset_id:'a1', input:{ asset_id:'a1', formulation_objective:'sustained_release', apis:[{name:'API One', dose_mg:10}], excipients:[{name:'PLGA', percentage:35, amount_mg:35, amount:35, unit:'mg'}], release_duration_weeks:4, route_of_administration:'SC', regulatory_body:'FDA', strategy_mode:'cooperative', optimize_excipient_percentages:true, pkpd_objective:{target_exposure:'range', dosing_interval_days:7, peak_to_trough_priority:3, adherence_priority:4}}, release_profile:{ labels:['Week 1'], datasets:[{api:'API One', cumulative_release:[25], model:'model', rationale:'rationale'}]}, scorecard:{ release_feasibility:{ score:80, rationale:'release rationale', assumptions:['assumption'], uncertainty:['uncertainty'], recommendation:'recommendation', next_best_step:'experiment' } }, overall_chronothera_score:80, formulation_delivery_profile:{ asset_dossier_link:'forge/a1' }, epistemic_trace:{ zone_cluster:'ChronoThera Formulation & Delivery Zone Cluster', zones:['Release Zone'], cxus:[{id:'CXU_RELEASE', name:'release CXU', question:'Can it release?', confidence:.8, uncertainty:['uncertainty']}], swarm:{ id:'CHRONOTHERA_FORMULATION_SWARM', mode:'cooperative', participants:['release CXU'], consensus_score:80, consensus_rationale:'consensus' }, provenance:{ input_hash:'abc', output_hash:'def', model_engine_version:'v1', timestamp:'2026', assumptions:['assumption'], uncertainty_reasons:['uncertainty'] } }, guardian_review:{ required:false, status:'not-required', reasons:[] }, disclaimer:'research use only' };
function wrap(ui: React.ReactElement){ return render(<QueryClientProvider client={new QueryClient({ defaultOptions:{ queries:{ retry:false }, mutations:{ retry:false } } })}>{ui}</QueryClientProvider>); }
beforeEach(()=>vi.unstubAllGlobals());

describe('ChronoThera internal module', () => {
 it('is not included in public homepage navigation and has no public open CTA', () => { const html=fs.readFileSync(path.join(process.cwd(),'..','index.html'),'utf8'); const nav=html.match(/<ul class="nav-links">([\s\S]*?)<\/ul>/)?.[1] ?? ''; expect(nav).not.toContain('ChronoThera'); expect(html).not.toContain('Open ChronoThera'); });
 it('renders with catalog data and populates asset presets', async () => { vi.stubGlobal('fetch', vi.fn((url:string, init?:RequestInit) => Promise.resolve({ ok:true, status:init?.method==='POST'?201:200, json:async()=> url.includes('catalog') ? catalog : [] }))); wrap(<ChronoTheraApp/>); expect(await screen.findByText('ChronoThera™ formulation intelligence')).toBeInTheDocument(); expect(await screen.findByDisplayValue('API One')).toBeInTheDocument(); });
 it('validates API and excipient selection before simulation', async () => { vi.stubGlobal('fetch', vi.fn((url:string) => Promise.resolve({ ok:true, status:200, json:async()=> url.includes('catalog') ? catalog : [] }))); wrap(<ChronoTheraApp/>); expect(await screen.findByText(/Select at least one excipient/)).toBeInTheDocument(); fireEvent.click(await screen.findByLabelText('select PLGA')); await waitFor(()=>expect(screen.queryByText(/Select at least one excipient/)).not.toBeInTheDocument()); expect(screen.getByLabelText('PLGA amount')).toBeInTheDocument(); expect(screen.getByLabelText('PLGA amount unit')).toBeInTheDocument(); });
 it('renders simulation response after request', async () => { vi.stubGlobal('fetch', vi.fn((url:string, init?:RequestInit) => Promise.resolve({ ok:true, status:init?.method==='POST'?201:200, json:async()=> url.includes('catalog') ? catalog : init?.method==='POST' ? simulation : [] }))); wrap(<ChronoTheraApp/>); fireEvent.click(await screen.findByLabelText('select PLGA')); fireEvent.click(screen.getByText('Run ChronoThera simulation')); expect(await screen.findByText(/ChronoThera readiness scorecard/)).toHaveTextContent('80'); expect(screen.getByText('release rationale')).toBeInTheDocument(); });
 it('scorecard renders rationales, assumptions, uncertainty, recommendations', () => { render(<ChronoTheraScorecard simulation={simulation}/>); expect(screen.getByText('release rationale')).toBeInTheDocument(); expect(screen.getByText('assumption')).toBeInTheDocument(); expect(screen.getByText('uncertainty')).toBeInTheDocument(); expect(screen.getByText(/experiment/)).toBeInTheDocument(); });
 it('EpistemicOS trace renders zones, CXUs, swarm, and provenance', () => { render(<EpistemicTracePanel simulation={simulation}/>); expect(screen.getByText('Release Zone')).toBeInTheDocument(); expect(screen.getByText(/release CXU/)).toBeInTheDocument(); expect(screen.getByText(/CHRONOTHERA_FORMULATION_SWARM/)).toBeInTheDocument(); expect(screen.getByText(/input abc/)).toBeInTheDocument(); });
 it('Guardian panel renders required and not-required states', () => { const { rerender }=render(<GuardianReviewPanel simulation={simulation}/>); expect(screen.getByText('Not required')).toBeInTheDocument(); rerender(<GuardianReviewPanel simulation={{...simulation, guardian_review:{...simulation.guardian_review, required:true, reasons:['low score']}}}/>); expect(screen.getByText('Required')).toBeInTheDocument(); expect(screen.getByText(/low score/)).toBeInTheDocument(); });
 it('JSON export creates a dossier artifact download', () => { const click=vi.fn(); vi.stubGlobal('URL', { createObjectURL: vi.fn(()=> 'blob:url'), revokeObjectURL: vi.fn() }); render(<JsonExportButton simulation={simulation}/>); const realCreate = document.createElement.bind(document); vi.spyOn(document, 'createElement').mockImplementation((tag: string) => tag === 'a' ? ({ click, set href(v:string){}, set download(v:string){} } as any) : realCreate(tag)); fireEvent.click(screen.getByText(/Export JSON/)); expect(click).toHaveBeenCalled(); });
});
